### ISSUE TITLE
std::allocator<void> deprecated in C++17

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/asio#109]
This warning appears when building with MSVC and `/std:c++17`

1>c:\users\vinnie\lib\boost_1_67_0\boost\asio\associated_allocator.hpp(103): warning C4996: 'std::allocator<void>': warning STL4009: std::allocator<void> is deprecated in C++17. You can define _SILENCE_CXX17_ALLOCATOR_VOID_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.

**Comment by mq1n** [comment]
Is there any actual solution for it?

**Comment by vinniefalco** [comment]
It looks like MSVC is doing the wrong thing here, see: https://github.com/chriskohlhoff/asio/issues/290#issuecomment-371867040
