### ISSUE TITLE
io_context replace io_service

### ISSUE THREAD

**Issue by snahmad** [boostorg/asio#110]
Should we been using io_context instead of io_service in latest boost.

**Comment by djarek** [comment]
`io_service` is deprecated. Yes, you should use `io_context`. Beware that the "old" API is deprecated as well (e.g. `io_service.post()`, you should use `post(io_context, handler)`).

**Comment by superlambchops** [comment]
Is there a guide to converting a program from using io_context to use io_service?

**Comment by djarek** [comment]
`io_context` -> `io_service`
`io_context.post()` -> `io_context.get_executor().post()`
`io_context.dispatch()` -> `io_context.get_executor().dispatch()`

`io_context::strand` -> `strand<io_context::executor_type>`

there were also changes to composed operation customization hooks - there are only 2 now - `boost::asio::associated_allocator` and `boost::asio::associated_executor`, which default to looking for `get_allocator()`, `get_executor()`, T::allocator_type, T::executor_type members of the composed operation function object.

This is not a complete list.

**Comment by GrumpyOldTroll** [comment]
Is there a doc outlining the reasons a non-backward-compatible change was required?  This is an unpleasant surprise, and pretty disruptive to existing projects using boost...

**Comment by DinoStray** [comment]
I feel terrible for the changes

**Comment by TorstenRobitzki** [comment]
@djarek In your list above, there is one thing missing. In earlier versions of asio, we could obtain the `io_context` from `get_io_service()` in serial_port or other IO objects. Now, `.get_executor().context()` returns the base class to `io_context` and a downcast is required. Is there an other solution to get the `io_context` from an existing IO object?

**Comment by thejohnfreeman** [comment]
> `io_context` -> `io_service`
> `io_context.post()` -> `io_context.get_executor().post()`
> `io_context.dispatch()` -> `io_context.get_executor().dispatch()`
> 
> `io_context::strand` -> `strand<io_context::executor_type>`

New user here. Is this supposed to mean "the left expression supersedes the right expression" or "change occurrences of the left expression to the one on the right"?

**Comment by IvanKush** [comment]
> Is there a doc outlining the reasons a non-backward-compatible change was required? This is an unpleasant surprise, and pretty disruptive to existing projects using boost...

I think due to Network TS. But now appears the question, why the WG have 
choosen `io_context `

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0112r0.html
