### ISSUE TITLE
resolver "everything" marked as deprecated, alternatives not supplied

### ISSUE THREAD

**Issue by xxxLCxxx** [boostorg/asio#127]
If I'm correct, Boost 1.67.0 is the latest. As you can see here
https://www.boost.org/doc/libs/1_67_0/doc/html/boost_asio/reference/ip__tcp/resolver.html
(Add link in this editor is not working, hurray. Preview neither - extra bonus!)
about everything you need to resolve is marked as deprecated:

async_resolve (Deprecated.) ...
resolve (Deprecated.) ...
query (Deprecated.) The query type.
iterator (Deprecated.) The iterator type.

This would render many of the examples deprecated as well, as the clients are using those functions for resolving.
What are we supposed to use for asynchronous lookups now?

**Comment by djarek** [comment]
Please check the documentation closely, it's clearly stated that only some overloads are deprecated.

**Comment by xxxLCxxx** [comment]
Shouldn't that be where the 'deprecated' is located?
=> this overload(!) is deprecated, use ... instead?
If you look for the resolver documentation and land at ip::tcp::resolver, this is far from clear.
Besides, it points to ip::basic_resolver, which has just the same deprecated entries without further information. This isn't the way to document things.

**Comment by xxxLCxxx** [comment]
Am I blind?
https://www.boost.org/doc/libs/1_67_0/libs/beast/doc/html/beast/quick_start.html
...
using tcp = boost::asio::ip::tcp;       // from <boost/asio/ip/tcp.hpp>
...
// Look up the domain name
auto const results = resolver.resolve(host, port);
...

Is that the 'deprecated' one - in your (Beast) current "Getting started" guide?
Which would be the correct (non deprecated) way?
*puzzled*

**Comment by xxxLCxxx** [comment]
forgot this in the middle:
tcp::resolver resolver{ioc};

**Comment by djarek** [comment]
The Beast guide uses this constructor: https://www.boost.org/doc/libs/1_67_0/doc/html/boost_asio/reference/ip__basic_resolver/resolve/overload3.html

**Comment by xxxLCxxx** [comment]
I finally understand what is meant. In the reference, when there are 'deprecated' member functions, this is being propagated upwards where then the entire/only member function description has a "(Deprecated.)" appended.
This seems to be automated. I would suggest turning that into something like "(1 of 7 deprecated)". This would be of more use to the 'creators' and a lot less misleading to anyone stumbling on the reference.

**Comment by arthur-tacca** [comment]
> it's ... stated that only some overloads are deprecated.

Correct

> it's clearly stated that only some overloads are deprecated. 

Not correct. (Clearly not correct 😉 )

I have had the same confusion before. The ideal solution would be to tweak the documentation generator so the distinction between overloads is clearer, but you *do* want overloads grouped together somewhat so imagine it would be very hard to get the balance right. The simpler solution is the one xxxLXxxx suggested: just change the text from "(deprecated)" to "(this overload is deprecated)" for the relevant functions.

**Comment by vinniefalco** [comment]
>The ideal solution would be to tweak the documentation generator...

Pull requests welcomed, the code to generate those docs is here:
https://github.com/boostorg/asio/blob/fbe86d86b1ac53e40444e5af03ca4a6c74c33bda/doc/reference.xsl#L1281

**Comment by srijanc** [comment]
I am still unable to figure out what exactly needs to be used in place of the "iterator" or any pre-existing is being used instead. Please provide some suggestions.
