### ISSUE TITLE
Wrong namespace for boost::asio::ip::make_address in the documentation 

### ISSUE THREAD

**Issue by Belgorodsky** [boostorg/asio#138]
In the documentation of 1.68.0 here:
https://www.boost.org/doc/libs/1_68_0/doc/html/boost_asio/reference/ip__address/make_address.html
"**ip::address::make_address**" in the title, but "**ip::make_address**" expected one

**Comment by ednolan** [comment]
This issue still exists in 1.72.0: https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/ip__address/make_address.html

**Comment by sly1061101** [comment]
still exists in 1.73 https://www.boost.org/doc/libs/1_73_0/doc/html/boost_asio/reference/ip__address/make_address.html

**Comment by mrakh** [comment]
Yep, this error had me scratching my head for a while.
