### ISSUE TITLE
10.0.10 treated as a invalid IPv4 address on macOS

### ISSUE THREAD

**Issue by sweatybridge** [boostorg/asio#146]
Calling `boost::asio::ip::make_address("10.0.10")` successfully returns a `boost::asio::ip::address` on Windows and Linux, but returns an error on macOS. This is due to macOS's `inet_pton` not accepting abbreviated inner zeros.

**Comment by zarath** [comment]
I don't know if there is a newer RFC that's prohibit the abreviation of IPv4 addresses.
In general even IPv4 addresses can be shortend, by leaving out inner zeros.
Even on current Linux ping 127.1  works.
10.1.10 schould be expanded to 10.1.0.10  and so on.

I would consider macOS's behaviour as wrong!

**Comment by sweatybridge** [comment]
Thank you for looking into this! According to macOS's manual https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/inet_pton.3.html, their implementation of `inet_pton` is behaving as expected.
```
STANDARDS
     The inet_ntop() and inet_pton() functions conform to X/Open Networking
     Services Issue 5.2 (``XNS5.2'').  Note that inet_pton() does not accept
     1-, 2-, or 3-part dotted addresses; all four parts must be specified and
     are interpreted only as decimal values.  This is a narrower input set
     than that accepted by inet_aton().
```

Can we change boost's `make_address_v4` implementation on macOS to call `inet_aton` instead?

As far as I can tell from https://www.boost.org/doc/libs/1_68_0/boost/asio/detail/impl/socket_ops.ipp, `inet_aton` is not exposed as part of boost's socket ops. So may be we can add a `#ifdef` to the current implementation of `inet_pton`.

The alternative option is document the difference on boost's platform specific implementation notes https://www.boost.org/doc/libs/1_68_0/doc/html/boost_asio/overview/implementation.html. But I'm not a fan of this approach because that documentation is difficult to find and may catch new users by surprise.

I would be great if boost can work more consistently across different platforms.

**Comment by krandell** [comment]
Not sure if this should be a new ticket, but relates to the inconsistency between implementations:
The Windows implementation is not behaving as documented - it will convert to octal or hexadecimal based on the prefix in each dotted section, like `inet_aton`. Therefore I think that either the documentation should change to state that other bases and abbreviated address are supported, and the Mac version should change to `inet_aton`, or the Windows version should change to behave like `inet_pton`.

The WinRT implementation currently appears to support dotted-decimal with exactly 4 parts, though I haven't tested it.
