### ISSUE TITLE
Coverity static analysis defects (Trac ticket #13331)

### ISSUE THREAD

**Issue by mloskot** [boostorg/asio#148]
(copied from https://svn.boost.org/trac10/ticket/13331, only Asio's parts from the attached report)

Boost 1.57.0

A static analysis tool called Coverity found medium and high defects in the boost source code. See attached file for defect type, defect category, filename and line number of defect. 

Defect   Type | Defect Category | Line Number | Filename
-- | -- | -- | --
Unchecked   return value from library | Error handling issues | 473 | /boost/include/boost/asio/detail/impl/epoll_reactor.ipp
Unchecked   return value from library | Error handling issues | 84 | /boost/include/boost/asio/detail/impl/eventfd_select_interrupter.ipp
Unchecked   return value from library | Error handling issues | 581 | /boost/include/boost/asio/detail/impl/signal_set_service.ipp
Unchecked   return value from library | Error handling issues | 500 | /boost/include/boost/asio/detail/impl/epoll_reactor.ipp
Unitialized   pointer field | Unitialized members | 54,55,58,59,60,62,606 | /boost/include/boost/asio/detail/impl/epoll_reactor.ipp
Out-of-bounds   access | Memory-corruptions | 385 | /boost/include/boost/asio/impl/read_until.hpp
Out-of-bounds   access | Memory-corruptions | 577 | /boost/include/boost/asio/impl/read_until.hpp
Uninitialized   scalar filed | Uninitialized members | 50 | /boost/include/boost/asio/detail/timer_queue.hpp
Unchecked   return value | Error handling issues | 46 | /boost/include/boost/asio/detail/posix_mutex.hpp

**Comment by vinniefalco** [comment]
Boost version 1.57.0? Or do you mean 1.67.0?

**Comment by mloskot** [comment]
I meant what I copied from the Trac ticket, without doing any verification though

![image](https://user-images.githubusercontent.com/80741/46862502-44e08500-ce15-11e8-9462-8c7c667fa1c9.png)

**Comment by vinniefalco** [comment]
Every Coverity anaysis on my own code that people have run for me, only turned up false positives. Your mileage may vary.
