### ISSUE TITLE
Does asio::async_read need extra support for cancellation

### ISSUE THREAD

**Issue by PlacidBox** [boostorg/asio#154]
Suppose I have an `asio::async_read` running that I wish to cancel, and call the `.cancel()` function on the socket. Is it possible that as I call cancel the async_read is between finishing one read and starting the next (since it's a composed operation)? 

Does asio already protect against this, or do I need to hook in to `CompletionCondition` somehow to prevent this

**Comment by djarek** [comment]
In theory, it is possible for the composed operation to be scheduled on your Executor behind the operation that performs `cancel()` which would cause it to be missed. Note, that calling `cancel()` on the underlying socket that is wrapped into a stream e.g. `boost::asio::ssl::stream<socket>` will result in the "top" stream being left in an invalid state.

**Comment by vinniefalco** [comment]
You can only cancel **all** I/O, you cannot cancel an individual read. Furthermore, socket objects are _not thread safe_. You have to call `cancel` from the same implicit or explicit strand as that used for the other operations.
