### ISSUE TITLE
Implicit conversion loses integer precision in socket_ops.ipp in Xcode macOS

### ISSUE THREAD

**Issue by runesig** [boostorg/asio#165]
Hi

I am getting the warning:

Implicit conversion loses integer precision: 'std::size_t' (aka 'unsigned long') to 'socklen_t' (aka 'unsigned int')

int the file socket_ops.ipp when compiling ASIO with Xcode.

<img width="1512" alt="screen shot 2018-11-12 at 07 10 11" src="https://user-images.githubusercontent.com/2069630/48329730-4ab2cb80-e64a-11e8-9d4f-8744ee83b8d1.png">

**Comment by pbhatkhande** [comment]
I have the same issue. Did you manage to fix this?

**Comment by runesig** [comment]
No, not really. After some research I decided to turn the warning "Implicit Conversion To 32 bit" off. I have not experienced any issues by doing so.
