### ISSUE TITLE
warning while using boost::asio::spawn

### ISSUE THREAD

**Issue by savagecm** [boostorg/asio#192]
boost::asio::spawn is based on boost::coroutine, but boost::coroutine is now deprecated. 
Any plan  to get spawn update with  Boost.Coroutine2?

**Comment by djarek** [comment]
#55

**Comment by vinniefalco** [comment]
The warning should be gone now:  https://github.com/boostorg/coroutine/commit/f226f9ba278fd531f9e723e7965e63c0c6d6fd10

**Comment by AndrewAMD** [comment]
> The warning should be gone now: [boostorg/coroutine@f226f9b](https://github.com/boostorg/coroutine/commit/f226f9ba278fd531f9e723e7965e63c0c6d6fd10)

If boost coroutine is deprecated, why was this warning removed?

**Comment by vinniefalco** [comment]
> If boost coroutine is deprecated, why was this warning removed?
Because users of Asio cannot do anything about the warning, so it is just noise. Until Asio is no longer dependent on Boost.Coroutine, the warning is not actionable.
