### ISSUE TITLE
Is it possible to bind a strand to a specific thread?

### ISSUE THREAD

**Issue by traceon** [boostorg/asio#194]
Is there any known technique to force all tasks of a specific strand to be executed only in a predefined thread(s) (that is, from run() or similar call, called on a specific thread.)

**Comment by djarek** [comment]
The only way of making sure that a completion handler runs on a specific thread is to make sure that it runs in an implicit strand (i.e. one `io_context` per thread).

**Comment by traceon** [comment]
I see, thank you @djarek
