### ISSUE TITLE
make_addr_v4 perform a copy of string in one of the overload

### ISSUE THREAD

**Issue by JohnCoconut** [boostorg/asio#196]
https://github.com/boostorg/asio/blob/a6008b6427ddfc3222f83c53030c34c802c53b59/include/boost/asio/ip/impl/address_v4.ipp#L193

Code copied below,

```cpp
address_v4 make_address_v4(string_view str)
{
  return make_address_v4(static_cast<std::string>(str));
}

address_v4 make_address_v4(string_view str,
    boost::system::error_code& ec)
{
  return make_address_v4(static_cast<std::string>(str), ec);
}
```

The following expression,
```cpp 
static_cast<std::string>(str)
```
construct a new string, copying the contents from string_view.

It's better to use the `const char*` overload by calling
```cpp
make_address_v4(str.data());
```

**Comment by 2underscores-vic** [comment]
`make_address_v4` implementation eventually needs null-terminated string. `std::string` is needed only to add `\0` to the `string_view` which is just pointer+size

**Comment by 2underscores-vic** [comment]
> Personally I feel the interface is confusing. I wouldn't expect string_view overload will always create a copy. 

Agree on this
