### ISSUE TITLE
Missing work guard in asynchronous composed algorithms

### ISSUE THREAD

**Issue by djarek** [boostorg/asio#202]
Algorithms that are composed operations and call more than one `async_*` suboperation (`boost::asio::async_read`, `boost::asio::async_write`, etc.) are missing an I/O executor `executor_work_guard` non-static data member.

**Comment by mabrarov** [comment]
Test reproducing this issue can be found at https://github.com/mabrarov/asio_samples/blob/feature/Beast_1450_no_work_guard_handler_with_custom_executor/examples/beast_echo_op/src/echo_op.cpp#L321
