### ISSUE TITLE
overlapped_ptr and custom object executors

### ISSUE THREAD

**Issue by djarek** [boostorg/asio#204]
It's not possible to construct an `overlapped_ptr` when dealing with type-erased or user-defined I/O executor types.

**Comment by vinniefalco** [comment]
Confirmed

**Comment by vinniefalco** [comment]
See https://github.com/boostorg/asio/pull/205

**Comment by vinniefalco** [comment]
Fixed here: https://github.com/boostorg/asio/commit/035775462e5c32d0112175745978f3627e7ee059
