### ISSUE TITLE
resolver self holding

### ISSUE THREAD

**Issue by g-glowacki** [boostorg/asio#217]
Hi,
I'm looking for a safe solution of using resolver in concurrent execution. I've come with an idea where the ResolveContext, can hold the resolver itself, is it safe?
```
struct ResolveContext
{
  public:
    ResolveContext(std::shared_ptr<boost::asio::ip::tcp::resolver> resolver, Connector connector);
        
    void operator()(const boost::system::error_code& ec, boost::asio::ip::tcp::resolver::iterator i);
private:
        std::shared_ptr<boost::asio::ip::tcp::resolver> resolver;
        ClientConnector io;
};

ResolveContext::ResolveContext(
    std::shared_ptr<boost::asio::ip::tcp::resolver> initialResolver,
    ClientConnector connector
    ) :
    resolver(std::move(initialResolver)),
    io(connector)
{
}

ResolveContext::operator()(
    const boost::system::error_code& ec,
    boost::asio::ip::tcp::resolver::iterator i)
{
   if (!ec)
   {
          this->io->Connect(i);
   }
}

```

And now can have a simple function with just one shared between threads ioService:
```
Connect(
   boost::asio::io_service& ioService,
   Connector connector,
    string host,
    string port
    )
{
    auto resolver = std::make_shared<boost::asio::ip::tcp::resolver>(ioService);
    ResolveContext context(
        resolver,
        std::move(connector));

    resolver->async_resolve(host, port, std::move(context));
}

```

**Comment by djarek** [comment]
If you're using asio 1.66+ or higher you can just use a `unique_ptr`:
```
auto resolver = std::make_unique<boost::asio::ip::tcp::resolver>(ioService);
auto& ref = *resolver;

ref.async_resolve(host, port,
  [r = std::move(resolver), c = std::move(connector)](error_code ec, auto it){
    if (!ec)
      c->Connect(it);
});
```

**Comment by travnick** [comment]
@djarek So in versions prior 1.66 it's unsafe to use such solution, why? Can you please provide more detailed explanation of why/why not. Is there any documentation about that?

I'm asking because it's quite important to me to provide a proof (if possible) that this piece of code is going to work correctly.

**Comment by djarek** [comment]
Prior to 1.66 ASIO required CompletionHandlers to be CopyConstructible, which would cause a compilation failure of the snippet I posted.

**Comment by travnick** [comment]
Oh, you were talking only about the support for move semantics here.

What about the safety of passing the "self" inside "this"? It looks like circular dependency issue, if somehow the `context` is stuck in some kind of queue (as documentation says, the request are waiting for resolution and it's possible to cancel them).

This is the possible issue I'm aware of and - unfortunately - documentation does not explain it very well.

**Comment by djarek** [comment]
Of course, if you don't retain any reference/pointer to the resolver, then you have no ability to cancel the operation, so it will be pending until the ExecutionContext the resolver uses is destroyed.
