### ISSUE TITLE
How to use async_compose() with different executors for implementation function and completion handler

### ISSUE THREAD

**Issue by traceon** [boostorg/asio#236]
According to this, the executor associated with the completion handler will be used:
https://github.com/boostorg/asio/blob/f2e6af2693df0a7603184d73d9f3e34d245fde71/include/boost/asio/impl/compose.hpp#L187-L190
Is it possible to somehow bind a different executor to the **implementation of the composed asynchronous operation** too, or I can't use `async_compose()` for that and I need to follow `cpp11/operations/composed_6.cpp` example and write my own?

**Comment by djarek** [comment]
Why would you want to override the handler's associated executor?

**Comment by traceon** [comment]
I don't want to override it for handler. I want to set a custom one for the code that runs before invoking the completion handler, e.g. when the implementation of the operation needs its own strand.

**Comment by djarek** [comment]
I don't think`async_compose` is the appropriate facility for this purpose. If you want to run some code on a different executor and invoke the handler on the associated executor, you'll need to manage `post`/`dispatch` appropriately on your own.
