### ISSUE TITLE
is beast and asio good enough for enterprise use? how about it compared to netty? and is there any famouse App/Website/Exe use beast and asio?

### ISSUE THREAD

**Issue by opengpu** [boostorg/asio#242]
is beast and asio good enough for enterprise use? how about it compared to netty?
and is there any famouse App/Website/Exe use beast and asio?

**Comment by 2underscores-vic** [comment]
Some info about Beast: https://github.com/boostorg/beast/wiki/Companies-and-Individuals-Using-Beast
