### ISSUE TITLE
Hash functions for addresses, endpoints

### ISSUE THREAD

**Issue by gumb0** [boostorg/asio#245]
It would be helpful to provide `std::hash` specializations for the types such as `ip::address`, `ip::tcp::endpoint`, `ip::udp::endpoint`, to make them usable with `std::unordered_map`, `std::unordered_set`

**Comment by nbougalis** [comment]
I think this is an excellent idea and if nobody else is interested in picking it up, I'll do it. Also, hello to my friends from the Ethereum world! :wave:
