### ISSUE TITLE
MSVC 14.2 compilation "warning C4242:  '=': conversion from 'int' to 'ADDRESS_FAMILY', possible loss of data"

### ISSUE THREAD

**Issue by wyattoday** [boostorg/asio#246]
When compiling an app using ASIO and a newer version of Visual Studio (for example, VS 2019) a bunch of warnings are emitted:

```
boost\asio\detail\impl\win_iocp_socket_service_base.ipp(609,32): warning C4242:  '=': conversion from 'int' to 'ADDRESS_FAMILY', possible loss of data (compiling source file XYZ.cpp)
```

The solution is, on line 609 of win_iocp_socket_service_base.ipp, change the line to this:

```
a.base.sa_family = static_cast<ADDRESS_FAMILY>(family);
```

Similarly, in `boost\asio\impl\serial_port_base.ipp(511,28): warning C4242:  '=': conversion from 'const unsigned int' to 'BYTE', possible loss of data (compiling source file GlobalVars.cpp)`:

Fix:

```
  storage.ByteSize = static_cast<BYTE>(value_);
```

**Comment by fsmoke** [comment]
I have the same issue - VS 2019 - x86 project configuration
