### ISSUE TITLE
Downgrade introduced by version 1.70 in basic_waitable_timer::async_wait (maybe also in boost::asio::post)

### ISSUE THREAD

**Issue by youngwolf-project** [boostorg/asio#247]
Before 1.55, an additional replication of the callback will happen before calling basic_waitable_timer::async_wait's callback (I feel it's not necessary).
Since 1.55, until 1.70, the additional replication has been eliminated.
But in 1.70, it came back again.

PS:
with c++0x or higher, above replication will not occur, but since 1.55, until 1.70, even without c++0x, it will not occur, so I feel it's a downgrade.

**Comment by vinniefalco** [comment]
Does this fix it?
https://github.com/boostorg/asio/commit/637f3404bd57ec764438c15bded128ae6cc82cdd

**Comment by youngwolf-project** [comment]
Seems it's exactly the root cause.
I didn't track the develop branch of boost, I'll verify it when I have time.

**Comment by youngwolf-project** [comment]
The mechanism I used to track the replication of callback handler is:
1. I have a boost::shared_ptr<char> aci;
2. Call boost::asio::post(io_context_, (aci, boost::lambda::bind(boost::lambda::unlambda(handler))));
3. In handler, check aci.use_count();
With boost 1.70 or before 1.55, we get 3 in step #3, otherwise, 2. No matter c++0x is opened or not.

Change step #2 to:
Call timer.async_wait((aci, boost::lambda::bind(boost::lambda::unlambda(handler), boost::lambda::_1)));
With boost 1.70 or before 1.55, we get 3 in step #3, otherwise, 2, but if open c++0x for boost 1.70, we get 2 too.
