### ISSUE TITLE
Error initializing tcp socket with boost::ref(io_context)

### ISSUE THREAD

**Issue by kkumar45** [boostorg/asio#252]
Initializing tcp::socket with boost::ref(io_context) results in compilation error.  It looks like a regression in boost::asio. 

It can be reproduced easily with below code. 

`#include <boost/asio.hpp>
#include <boost/core/ref.hpp>

int main()
{
    boost::asio::io_context io_context;
    boost::asio::ip::tcp::socket socket(boost::ref(io_context));
    return 0;
}
`

Error details :
boost/asio/detail/io_object_impl.hpp:101:40: error: ‘const class boost::reference_wrapper<boost::asio::io_context>’ has no member named ‘get_executor’; did you mean ‘get_pointer’?
       implementation_executor_(context.get_executor(),
                                ~~~~~~~~^~~~~~~~~~~~

I have attached a patch, which works as a workaround for the issue. (file: boost/asio/detail/io_object_impl.hpp)

![io_object_impl](https://user-images.githubusercontent.com/26009849/59086755-4de01280-8920-11e9-8c66-37411b7306df.JPG)

**Comment by djarek** [comment]
https://github.com/boostorg/asio/issues/227
