### ISSUE TITLE
async_result for use_awaitable_t should expose completion_handler_type not handler_type

### ISSUE THREAD

**Issue by cstratopoulos** [boostorg/asio#256]
As per the [`async_result` docs](https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/reference/async_result.html), specializations of `async_result` should expose `completion_handler_type`, but instead we currently have `handler_type`: https://github.com/boostorg/asio/blob/develop/include/boost/asio/impl/use_awaitable.hpp#L237

**Comment by djarek** [comment]
`completion_handler_type` is no longer required by the new form: https://github.com/boostorg/asio/commit/0568d3bf0b492887c6c48d05f5492a782dafa746
