### ISSUE TITLE
winrt_ssocket_service::shutdown: function does not take 3 arguments (1.69.0)

### ISSUE THREAD

**Issue by avakhrushev** [boostorg/asio#258]
Using boost::asio::ip::tcp::socket::shutdown(tcp::socket::shutdown_both, ec);
(Edit: referenced indirectly from basic_socket::shutdown)
I get this error during build:
'boost::asio::detail::winrt_ssocket_service<Protocol>::shutdown': function does not take 3 arguments

It appears winrt_ssocket_service does not in fact declare shutdown() with three parameters; it is declared at https://github.com/boostorg/asio/blob/boost-1.69.0/include/boost/asio/detail/winrt_ssocket_service_base.hpp#L168

Is this a bug, and I should just declare missing shutdown() in winrt_ssocket_service, 
or am I missing some steps necessary for WinRT in configuration maybe?

**Comment by djarek** [comment]
The function definition you linked does have 3 arguments.

**Comment by avakhrushev** [comment]
Yes it does. It is still not declared and is not available in the class that is actually used. Winrt_ssocket_service and winrt_ssocket_service_base are different classes.

**Comment by djarek** [comment]
Oh, right, I missed the `_base` suffix in the name.

**Comment by avakhrushev** [comment]
Appears to have been addressed https://github.com/boostorg/asio/commit/78f22b5a6e77aeb8c63c876d6b41d22d936d3b2b#diff-bb37c96539aea0e4b0de780b82b94890
