### ISSUE TITLE
boost::asio::strand suspected of having a memory leak?

### ISSUE THREAD

**Issue by luoyefeisong** [boostorg/asio#259]
When I used VS2017 for heap analysis, I found that my <class Peer> has been destructed, but the boost::asio::strand applied for some memory that was not freed.

**my code:**
![image](https://user-images.githubusercontent.com/13747710/61107526-b3409980-a4b2-11e9-86ba-b7b173c8b89a.png)

![image](https://user-images.githubusercontent.com/13747710/61107535-bc316b00-a4b2-11e9-8aaf-e59677a11480.png)

**heap analysis:**
![image](https://user-images.githubusercontent.com/13747710/61107637-fdc21600-a4b2-11e9-8902-0ab842ddedeb.png)
![image](https://user-images.githubusercontent.com/13747710/61107673-12061300-a4b3-11e9-9a48-1d08e1842cc6.png)
![image](https://user-images.githubusercontent.com/13747710/61107689-1af6e480-a4b3-11e9-8f58-7afe3f4e7447.png)
![image](https://user-images.githubusercontent.com/13747710/61107704-23e7b600-a4b3-11e9-99b6-7284da8b06cc.png)

**Comment by luoyefeisong** [comment]
version: 1.67.0

**Comment by djarek** [comment]
Note that the mutex pool is only destroyed when the service is destroyed (by `~io_context()`). Is `io_context` a global variable? Did you perhaps, leak it in some way?

**Comment by luoyefeisong** [comment]
> Note that the mutex pool is only destroyed when the service is destroyed (by `~io_context()`). Is `io_context` a global variable? Did you perhaps, leak it in some way?
Thank you for your reply. my 'io_context' is indeed a global variable, so should 'strand' also be set to a global variable?

**Comment by djarek** [comment]
No, making `strand` a global variable is not a solution. In fact, I don't think you have a problem here - the memory will be released after `io_context` is destroyed, so this is not a leak.

**Comment by luoyefeisong** [comment]
> No, making `strand` a global variable is not a solution. In fact, I don't think you have a problem here - the memory will be released after `io_context` is destroyed, so this is not a leak.

Okay, I see, thank you.
But there is a problem, we wrote a `server class` based on `boost::asio`, each time a new `connection class` will create a `strand`. And disconnected, after the `connection class` is destructed, the memory generated by the `strand` is not released.
`io_context` is a member variable of the `server class`.In this case, every new connection will be accompanied by memory growth, but the `server class` will always be maintained.
How can I fix this problem?

**Comment by djarek** [comment]
The number of mutexes in the mutex table is bounded: https://github.com/boostorg/asio/blob/develop/include/boost/asio/detail/strand_executor_service.hpp#L120 so not every `strand` object will cause "allocated memory growth".

**Comment by luoyefeisong** [comment]
Thank you!
I checked it, it is right.
