### ISSUE TITLE
asio::async_read_until/asio::read_until is significantly slower on Windows 10

### ISSUE THREAD

**Issue by LukePowell** [boostorg/asio#263]
Reading from a serial device until reaching a given delimiter is significantly slower on Windows 7 vs Windows 10.

Boost Versions: 1.64.0 - 1.7.0

Windows 7: ~7 milliseconds to read until the delimiter
Windows 10: ~81 milliseconds to read until the delimiter

**Comment by djarek** [comment]
Could it be an issue in the implementation in Windows?

**Comment by LukePowell** [comment]
Entirely possible, have yet to step through or profile asio::read_until to see if there is an obvious issue with its Windows implementation.
