### ISSUE TITLE
boost socket async_wait issue

### ISSUE THREAD

**Issue by wangjiangw** [boostorg/asio#277]
hi, all

i have an confusing question today，in my code，i had register a handler on socket by using async_wait，code like below

ssl_socket_->next_layer().async_wait(ip::tcp::socket::wait_error, handler);

however, when the handler called later, the error_code showed is 0，and the error message is success, can anyone help me or tell me why ?

**Comment by djarek** [comment]
`async_wait()` on a socket should only be used if you're using the socket in reactor-style code. `ip::tcp::socket::wait_error` doesn't mean that you'll wait until an error, but instead, you'll wait until there's OOB data on the socket (equivalent to the err_fd set in `select()`)

**Comment by wangjiangw** [comment]
> `async_wait()` on a socket should only be used if you're using the socket in reactor-style code. `ip::tcp::socket::wait_error` doesn't mean that you'll wait until an error, but instead, you'll wait until there's OOB data on the socket (equivalent to the err_fd set in `select()`)

ok, thanks for your answer
from your answer，i have a question，that is, once the handler has been called on wait_error, the error_code in handler will always be 0 ? or just in some situations ？

**Comment by djarek** [comment]
If you call `cancel()` on the socket the error will be non-zero say something like `operation aborted`. In general this will complete any time you get an OOB event on the socket. Some more info here: https://stackoverflow.com/a/591104
