### ISSUE TITLE
Boost Asio doesn't provide move semantic for handlers

### ISSUE THREAD

**Issue by ecoindev** [boostorg/asio#285]
Boost Asio doesn't provide move semantic for handlers:

```
    boost::asio::io_context io;
    auto uniq = std::make_unique<std::string>("Blah blah blah");
    io.post([uniq = std::move(uniq)](){});
```

error: call to implicitly-deleted copy constructor

Example: https://wandbox.org/permlink/oLbaRj7MBGWDSJeU

**Comment by ecoindev** [comment]
Oh my God! I need to check my code. I still use this legacy code everywhere :-)

Thanks!

**Comment by vinniefalco** [comment]
Define `BOOST_ASIO_NO_DEPRECATED` in your project to get help from the compiler

**Comment by ecoindev** [comment]
Thanks a lot!
