### ISSUE TITLE
What is the maintenance rate of this repos?

### ISSUE THREAD

**Issue by tomay3000** [boostorg/asio#287]
Hello,
Is this repo actively maintained?
Because I don't see any commits from the pull requests, or they are merged in a separate branch or repo!

TIA.

**Comment by 2underscores-vic** [comment]
Development is done in [chriskohlhoff/asio](https://github.com/chriskohlhoff/asio). But the author almost never replies in the issues. Although fixes some bugs couple of times a year

**Comment by tomay3000** [comment]
> Development is done in [chriskohlhoff/asio](https://github.com/chriskohlhoff/asio). But the author almost never replies in the issues. Although fixes some bugs couple of times a year

Ok, that makes sense then.

**Comment by vinniefalco** [comment]
It is well maintained, please close this issue.

**Comment by tomay3000** [comment]
@vinniefalco sure I am gonna close it, but I have one more question for you, the main purpose I have opened this issue is because `boost::asio::serial_port` that has this bug #290 which in turns is a duplicate of this one #280 and has been caused by this one c113adc and a final pull request that this fixes the last one, has not been taken care of, or merged. take a look here: #273

Thank you.

**Comment by vinniefalco** [comment]
Well those are separate issues. I know that the author is active, they have added new code 2 days ago.
