### ISSUE TITLE
Is boost::asio::ssl cache the data ?

### ISSUE THREAD

**Issue by new-commer** [boostorg/asio#289]
I'm using boost::asio::ssl  in my server , i have a problem .
Sometimes it didn't send the data to peer(I checked it by tcpdump) , even though it succeed call boost::asio::async_write.
In this case . Client will never receive the data no matter how long it wait . Unless it send another request to server. Then the data it expected arrived with a new data sent by server .
Is boost cache the data ? How can i resolve it ?

**Comment by vinniefalco** [comment]
No, boost is not caching the data. Something is wrong with your server. Have you tried building and running the examples to verify that they work?
