### ISSUE TITLE
The fuction boost::system::error_code win_iocp_serial_port_service::open( win_iocp_serial_port_service::implementation_type& impl, const std::string& device, boost::system::error_code& ec) returns error always

### ISSUE THREAD

**Issue by dshadrin** [boostorg/asio#293]
I boost version 1.71 in file boost\asio\detail\impl\win_iocp_serial_port_service.ipp on line 87 was inserted
dcb.BaudRate = 0; // 0 baud by default
but it is incorrected value for followed call of SetCommState.
GetLastError() return 87.

This is breakage because at least boost version 1.68 this function works correct.

**Comment by dshadrin** [comment]
Duplicate of #280

**Comment by Roman-Bober** [comment]
Same with me, when fixing dcb.BaudRate to correct value, "open" works flawlessly
My workaround was :
to take "open" method  code out and create HANDLE  to COM port separately 
and when create serial_port object with handle from above
