### ISSUE TITLE
Cannot compile 1.72.0 on Windows using Visual Studio 2019 with /std:c++latest

### ISSUE THREAD

**Issue by felixhao28** [boostorg/asio#325]
The source of boost library is acquired from https://www.boost.org/users/history/version_1_72_0.html .

As the title indicates, compilation fails on boost 1.72.0 while 1.71.0 works fine with /std:c++latest on Visual Studio 2019. And /std:c++17 works fine too.

Not sure this is a bug with Visual Studio or boost library. [I opened an issue for Visual Studio team](https://developercommunity.visualstudio.com/content/problem/909011/failed-to-compile-boost-1720-with-stdclatest.html), too.

**Comment by felixhao28** [comment]
This might be a duplicate of #312

**Comment by velia-ai** [comment]
I experienced the exact same problem and confirm that boost 1.72.0 w/ VS-2019 compiled fine when the language flag is set to /std:c++17 but failed when set to  /std:c++latest
