### ISSUE TITLE
100% CPU after waking from sleep (reported from qBT, Windows 10) 

### ISSUE THREAD

**Issue by rafi-d** [boostorg/asio#330]
https://github.com/arvidn/libtorrent/issues/2977#issuecomment-596195153
https://github.com/qbittorrent/qBittorrent/issues/7104

Reproduced by  terminating the interruptor socket here:
https://github.com/arvidn/libtorrent/issues/2977#issuecomment-596195153

**Comment by arvidn** [comment]
I think a more accurate title for this ticket is "socket_select_interrupter busy loop when waking up from sleep".

I also don't think this is the right github project to file this ticket against.

**Comment by rafi-d** [comment]
Which project is the right one?

**Comment by arvidn** [comment]
https://github.com/chriskohlhoff/asio/issues/461

**Comment by rafi-d** [comment]
> 
> 
> [chriskohlhoff/asio#461](https://github.com/chriskohlhoff/asio/issues/461)

Great, seems like you have succeeded to reproduce & w/a (fix) it in there. 

Since that project is not updating release that often, will you include your own fix (1.7.2  mod?) with libtorrent/qBT for now, till they will update asio in there?
