### ISSUE TITLE
VS2010 incompatible issue

### ISSUE THREAD

**Issue by CarlGitHub** [boostorg/asio#365]
boost 1.74.0

1>\boost_1_74_0\boost\asio\detail\impl\strand_executor_service.hpp(255): error C2244: 'boost::asio::detail::strand_executor_service::execute' : unable to match function definition to an existing declaration
1>        definition
1>        'void boost::asio::detail::strand_executor_service::execute(const boost::asio::detail::strand_executor_service::implementation_type &,Executor &,const Function &,enable_if<!boost::asio::can_query<Executor,boost::asio::execution::allocator_t<void>>::value>::type *)'
1>        existing declarations
1>        'void boost::asio::detail::strand_executor_service::execute(const boost::asio::detail::strand_executor_service::implementation_type &,Executor &,const Function &,enable_if<!boost::asio::can_query<Executor,boost::asio::execution::allocator_t<void>>::value>::type *)'
1>        'void boost::asio::detail::strand_executor_service::execute(const boost::asio::detail::strand_executor_service::implementation_type &,Executor &,const Function &,enable_if<boost::asio::can_query<Executor,boost::asio::execution::allocator_t<void>>::value>::type *)'

**Comment by Rezasdemon** [comment]
Dependencies\boost_1_74_0\boost/asio/detail/impl/strand_executor_service.hpp(255): error C2244: 'boost::asio::detail::strand_executor_service::execute' : unable to match function definition to an existing declaration

**Comment by Ruffletuft** [comment]
Test boost1.74 with VS2010,same as op. 
Test boost1.68 with VS2010,ok.
Test boost1.74 with VS2019,ok.
I guess it's a compatibility issue.

**Comment by Rezasdemon** [comment]
yeah 1.7 was working for me on 2010 also
