### ISSUE TITLE
asio fatal error: winapifamily.h: No such file or directory

### ISSUE THREAD

**Issue by sergiyvelichkevych** [boostorg/asio#387]
Building the project in Ubuntu 20 with g++11 with boost 1.78
with 

#include <boost/asio/ssl.hpp>

Got error:
/vcpkg/installed/x64-linux/include/boost/asio/detail/config.hpp:1320:12: fatal error: winapifamily.h: No such file or directory

It looks like broken defines for detecting OS

**Comment by ulatekh** [comment]
You appear to be building the vcpkg version under Linux.
Isn't the vcpkg variant specific to MS Windows?

**Comment by sergiyvelichkevych** [comment]
It was my mistake. I defined specific windows value  in my code and Linux builds failed because of this.
