### ISSUE TITLE
Boost.Asio initializes winsock to 2.0 instead of 2.2

### ISSUE THREAD

**Issue by jcelerier** [boostorg/asio#426]
https://github.com/boostorg/asio/blob/2e49b21732e5d1bb3bb98f209164c30816b0bc79/include/boost/asio/detail/winsock_init.hpp#L51C1-L51C1

Winsock 2.2 has apparently been available since Windows 95. Would it be possible to raise the version?

**Comment by xavier2k6** [comment]
https://github.com/boostorg/asio/blob/2e49b21732e5d1bb3bb98f209164c30816b0bc79/include/boost/asio/detail/winsock_init.hpp#L51-L52

**Comment by xavier2k6** [comment]
This can be closed, changes were implemented in https://github.com/chriskohlhoff/asio/commit/ee3bc5c89d310ee994073ba68ca35cb64332f8fd & will be included in Boost 1.85.0
