### ISSUE TITLE
ASIO always requires threading to be enabled

### ISSUE THREAD

**Issue by djarek** [boostorg/asio#63]
```cpp
#include <boost/asio/io_context.hpp>

int main()
{
    boost::asio::io_context srv;
    srv.post([](){});
    srv.run();
}
```
Requires -pthread compiler switch. The equivalent snippet compiled just fine without threading before 1.66.
I believe this is caused by the associated_executor<> trait having system_executor as the fallback executor.

**Comment by chriskohlhoff** [comment]
Use `BOOST_ASIO_DISABLE_THREADS` if you want to disable thread support.

Technically, asio has always required pthread support. It "worked" in the past because glibc provides stubs for some pthread functions as weak symbols.
