### ISSUE TITLE
boost::asio::buffer includes null character when used with string literal

### ISSUE THREAD

**Issue by martijnotto** [boostorg/asio#70]
When using boost::asio::buffer with a string literal, the buffer includes the terminating null character, which is not what one would expect.

This could be solved with something like this:

``` cpp
/// Create a new non-modifiable buffer that represents the given character array.
/**
  * @returns A const_buffer value equivalent to:
  * @code const_buffer(
  *     static_cast<const void*>(data),
  *     N * sizeof(char)); @endcode
  */
template <std::size_t N>
inline BOOST_ASIO_CONST_BUFFER buffer(
    const char (&data)[N]) BOOST_ASIO_NOEXCEPT
{
  return BOOST_ASIO_CONST_BUFFER(data, (N - 1) * sizeof(char));
}
```

But this might cause trouble when using a const char array that is not null-terminated, since we then basically drop the last character.

**Comment by chriskohlhoff** [comment]
Won't fix. This will break code, as this overload is used for arrays that are not string literals.
