### ISSUE TITLE
need SNI support

### ISSUE THREAD

**Issue by zynfly** [boostorg/asio#72]
It's good to be able to have a library that can provide such a simple network development.This makes the job very simple.But the support for SSL is not yet perfect.like SNI,and more.

**Comment by arvidn** [comment]
you can always do it [by hand](https://github.com/arvidn/libtorrent/blob/master/src/session_impl.cpp#L349) by getting the ``SSL_CTX``.

**Comment by zynfly** [comment]
Is it better to unify the interface?
To call the OpenSSL function in the ASIO program  is too ugly.
