### ISSUE TITLE
async_resolve endpoint overload is blocking on Windows

### ISSUE THREAD

**Issue by sweatybridge** [boostorg/asio#73]
I ran into this problem while trying to do multiple reverse lookups simultaneously. Each lookup is using a unique instance of `endpoint::resolver`. However, the resolution did not happen asynchronously. A similar problem has been posted on the user list back in 2014: https://lists.boost.org/boost-users/2014/12/83445.php

May I suggest that we update the documentation so that software engineers are aware of such issues in the future?
 http://www.boost.org/doc/libs/1_64_0/doc/html/boost_asio/reference/ip__basic_resolver/async_resolve/overload2.html

**Comment by vinniefalco** [comment]
But the documentation already states that asynchronous name resolutions on Windows are simulated using a thread that the asio implementation provides?

**Comment by sweatybridge** [comment]
That would indeed be sufficient. But I was not able to find that statement anywhere. Are we possibly looking at different documentation pages?

**Comment by vinniefalco** [comment]
See **Windows NT, 2000, XP, 2003, Vista, 7 and 8**

http://www.boost.org/doc/libs/1_65_1/doc/html/boost_asio/overview/implementation.html#boost_asio.overview.implementation.windows_nt__2000__xp__2003__vista__7_and_8

* *An additional thread per io_service is used to emulate asynchronous host resolution. This thread is created on the first call to either `ip::tcp::resolver::async_resolve()` or `ip::udp::resolver::async_resolve()`.*

**Comment by sweatybridge** [comment]
:) that and also I've not tried enough permutations of search terms.

**Comment by vinniefalco** [comment]
Check out Boost.Beast, HTTP and WebSocket using Boost.Asio:
https://github.com/boostorg/beast
