### ISSUE TITLE
Documentation refers to copying handlers

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/asio#92]
Documentation for async operations states that copies of the handler will be made as needed but this is not always correct, the handlers are moved when possible.

**Comment by RedDwarf69** [comment]
I noticed that from https://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/reference/Handler.html to https://www.boost.org/doc/libs/1_67_0/doc/html/boost_asio/reference/Handler.html it changed from:

`A handler must meet the requirements of CopyConstructible types (C++ Std, 20.1.3).`

to 

`A handler must meet the requirements of MoveConstructible types (C++Std [moveconstructible]).

(In https://www.boost.org/doc/libs/1_67_0/doc/html/boost_asio/overview/cpp2011/move_handlers.html it still says `However, handler types are still required to be copy constructible.`, though.)

So I guess `the handlers are moved when possible.` now is `the handlers are always moved`?
