### ISSUE TITLE
[OPEN] Missing header files or incorrect path?

### ISSUE THREAD

**Issue by johnalupton** [boostorg/asio#98]
Hi - I just cloned the current master version and am trying a test compile of a "Hello world", just to check my basic installation is ok before i start working through the tutorial.

My problem is that **a number of sub-include header files can not be found by asio.hpp** 😕 

**Pre-compile error thrown**
`cannot open source file "boost/config.hpp" (dependency of "boost/asio/associated_allocator.hpp")`

The only `config.hpp` file that I can find resides in 
`<project root dir>\asio\include\boost\asio\detail\config.hpp`

**Set up process**
I added latest master [boostorg/asio.git](https://github.com/boostorg/asio/commit/c30ed33c5edf5b8d2bdbbfec125139889d69e136) following github instuctions on how [work with submodules](https://blog.github.com/2016-02-01-working-with-submodules/)

`git submodule add https://github.com/boostorg/asio.git asio`

and recursively added the submodule beneath my project root directory

`git submodule update --init --recursive`

This has created the directory structure

`<project root dir>/asio/include/boost/...`

**Comment by johnalupton** [comment]
From the boost website, I added the following files beneath the directory 
`<project root dir>/asio/include/boost/`

[loads more than this ...]

http://www.boost.org/doc/libs/1_66_0/boost/assert.hpp
http://www.boost.org/doc/libs/1_66_0/boost/config.hpp
http://www.boost.org/doc/libs/1_66_0/boost/cstdint.hpp
http://www.boost.org/doc/libs/1_66_0/boost/is_placeholder.hpp
http://www.boost.org/doc/libs/1_66_0/boost/noncopyable.hpp
http://www.boost.org/doc/libs/1_66_0/boost/limits.hpp
http://www.boost.org/doc/libs/1_66_0/boost/regex_fwd.hpp
http://www.boost.org/doc/libs/1_66_0/boost/throw_exception.hpp
http://www.boost.org/doc/libs/1_66_0/boost/version.hpp

http://www.boost.org/doc/libs/1_66_0/boost/bind/arg.hpp

http://www.boost.org/doc/libs/1_66_0/boost/config/auto_link.hpp
http://www.boost.org/doc/libs/1_66_0/boost/config/workaround.hpp

http://www.boost.org/doc/libs/1_66_0/boost/config/detail/select_compiler_config.hpp

http://www.boost.org/doc/libs/1_66_0/boost/detail/workaround.hpp

http://www.boost.org/doc/libs/1_66_0/boost/date_time/posix_time/posix_time.hpp

http://www.boost.org/doc/libs/1_66_0/boost/system/api_config.hpp
http://www.boost.org/doc/libs/1_66_0/boost/system/config.hpp
http://www.boost.org/doc/libs/1_66_0/boost/system/error_code.hpp

http://www.boost.org/doc/libs/1_66_0/boost/predef/platform.h
http://www.boost.org/doc/libs/1_66_0/boost/predef/version_number.h

http://www.boost.org/doc/libs/1_66_0/boost/predef/platform/

http://www.boost.org/doc/libs/1_66_0/boost/predef/os/ios.h
http://www.boost.org/doc/libs/1_66_0/boost/predef/os/windows.h

http://www.boost.org/doc/libs/1_66_0/boost/predef/detail/os_detected.h
http://www.boost.org/doc/libs/1_66_0/boost/predef/detail/platform_detected.h
http://www.boost.org/doc/libs/1_66_0/boost/predef/detail/test.h

**Comment by johnalupton** [comment]
Ok, so I spent hours not getting a clean compile of a test program that simply included asio: Are there any install guides anywhere? I have tried finding something to no avail ... 😕

**Comment by purefan** [comment]
none that I have found, makes the whole asio thing feel like dark magic

**Comment by Skillotic0703** [comment]
I have the same problem! There is no file config.hpp in the directory boost

**Comment by jeking3** [comment]
Some time this past year, Boost.Build was changed to automatically execute the "./b2 headers" step which it looks like you have have omitted.  This would have caused your missing header in the past.
